import hashlib
import json
import re
from pathlib import Path

from x8.project_builder.contracts import GeneratedProjectFile, GeneratedProjectPlan, ProjectBuilderRequest, ProjectBuilderResult, ProjectBuilderStatus


class ProjectBuilderManager:
    def __init__(self, workspace_root: str = "/workspace", sandbox_path: str = "") -> None:
        self.workspace_root = Path(workspace_root).resolve()
        configured = Path(sandbox_path) if sandbox_path else self.workspace_root / "runtime" / "generated-projects"
        self.sandbox_root = configured.resolve()

    def preview(self, request: ProjectBuilderRequest) -> ProjectBuilderResult:
        plan = self._plan(request)
        return ProjectBuilderResult(
            status=ProjectBuilderStatus.PREVIEW,
            message="Project preview created. No files written until approved with the matching manifest_hash.",
            plan=plan,
            wrote_files=False,
            receipt=self._receipt("project_builder.preview", "preview", plan),
        )

    def write(self, request: ProjectBuilderRequest) -> ProjectBuilderResult:
        plan = self._plan(request)
        if not request.approved:
            return self._blocked(plan, "Project write requires approved=true.")
        if request.manifest_hash != plan.manifest_hash:
            return self._blocked(plan, "Project write requires the exact preview manifest_hash.")
        output = Path(plan.output_path).resolve()
        if not self._inside(output, self.sandbox_root):
            return self._blocked(plan, "Project output path is outside the approved sandbox.")
        output.mkdir(parents=True, exist_ok=True)
        written: list[str] = []
        for file in plan.files:
            target = (output / file.path).resolve()
            if not self._inside(target, output):
                return self._blocked(plan, f"Generated file path escaped project output: {file.path}")
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(file.content, encoding="utf-8")
            written.append(str(target))
        return ProjectBuilderResult(
            status=ProjectBuilderStatus.WRITTEN,
            message=f"Project written to {output}.",
            plan=plan,
            wrote_files=True,
            written_files=written,
            receipt=self._receipt("project_builder.write", "written", plan, {"written_files": written}),
        )

    def _plan(self, request: ProjectBuilderRequest) -> GeneratedProjectPlan:
        slug = self._slug(request.project_name or "x8-generated-project")
        output = (self.sandbox_root / slug).resolve()
        files = self._files(slug, request.prompt)
        manifest_body = {
            "project_name": request.project_name,
            "project_slug": slug,
            "generator": "x8_project_builder_mvp",
            "template": "adas_workflow_command_center" if self._is_adas_prompt(request.prompt) else "default_static_web_app",
            "requirements_matched": self._requirements_matched(request.prompt),
            "files": [{"path": file.path, "sha256": file.sha256, "size_bytes": file.size_bytes} for file in files],
            "safe_actions": ["preview_manifest", "write_to_sandbox_after_approval"],
            "blocked_actions": ["write_outside_sandbox", "overwrite_without_approval", "run_shell_from_chat"],
        }
        manifest_text = json.dumps(manifest_body, indent=2, sort_keys=True) + "\n"
        files = [
            GeneratedProjectFile(path="manifest.json", content=manifest_text, sha256=self._hash(manifest_text), size_bytes=len(manifest_text.encode("utf-8"))),
            *files,
        ]
        manifest_hash = self._hash("\n".join(f"{file.path}:{file.sha256}" for file in files))
        return GeneratedProjectPlan(
            project_name=request.project_name,
            project_slug=slug,
            sandbox_root=str(self.sandbox_root),
            output_path=str(output),
            manifest_hash=manifest_hash,
            files=files,
            safe_actions=["preview_manifest", "write_to_sandbox_after_approval"],
            blocked_actions=["write_outside_sandbox", "run_arbitrary_shell", "auto_commit", "auto_push"],
        )

    def _files(self, slug: str, prompt: str) -> list[GeneratedProjectFile]:
        if self._is_adas_prompt(prompt):
            return self._adas_files(slug, prompt)
        return self._default_files(slug, prompt)

    def _default_files(self, slug: str, prompt: str) -> list[GeneratedProjectFile]:
        title = self._title(slug)
        readme = f"# {title}\n\nGenerated by XV8 Project Builder MVP.\n\nPrompt summary: {prompt[:240] or 'small web app scaffold'}\n\nOpen `index.html` in a browser to run the app.\n"
        html = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>""" + title + """</title>
    <link rel="stylesheet" href="./src/styles.css" />
  </head>
  <body>
    <main class="app">
      <section class="workspace">
        <p class="eyebrow">XV8 generated project</p>
        <h1>""" + title + """</h1>
        <p id="summary">A small local web project written only after sandbox approval.</p>
        <button id="action" type="button">Mark ready</button>
        <pre id="receipt"></pre>
      </section>
    </main>
    <script src="./src/main.js"></script>
  </body>
</html>
"""
        js = """const button = document.querySelector('#action');
const receipt = document.querySelector('#receipt');

button?.addEventListener('click', () => {
  const payload = {
    status: 'ready',
    generatedBy: 'XV8 Project Builder MVP',
    checkedAt: new Date().toISOString()
  };
  receipt.textContent = JSON.stringify(payload, null, 2);
});
"""
        css = """body {
  margin: 0;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  background: #f4f7f8;
  color: #172126;
}

.app {
  min-height: 100vh;
  display: grid;
  place-items: center;
  padding: 32px;
}

.workspace {
  width: min(680px, 100%);
  border: 1px solid #c8d4d8;
  border-radius: 8px;
  background: #ffffff;
  padding: 28px;
  box-shadow: 0 14px 40px rgba(23, 33, 38, 0.12);
}

.eyebrow {
  margin: 0 0 8px;
  color: #33658a;
  font-size: 0.78rem;
  font-weight: 700;
  text-transform: uppercase;
}

h1 {
  margin: 0 0 12px;
  font-size: 2rem;
}

button {
  min-height: 40px;
  border: 0;
  border-radius: 6px;
  background: #2f7d6d;
  color: #fff;
  font-weight: 700;
  padding: 0 16px;
}

pre {
  min-height: 64px;
  overflow: auto;
  margin-top: 18px;
  padding: 12px;
  border-radius: 6px;
  background: #eef3f4;
}
"""
        return [
            self._file("README.md", readme),
            self._file("index.html", html),
            self._file("src/main.js", js),
            self._file("src/styles.css", css),
        ]

    def _adas_files(self, slug: str, prompt: str) -> list[GeneratedProjectFile]:
        title = "ADAS Workflow Command Center"
        readme = """# ADAS Workflow Command Center

Generated by XV8 Project Builder.

## Open locally

Open `index.html` in a browser from this folder. The app is plain frontend code and does not require paid APIs, secrets, a build step, Git commits, or network access.

## Included proof features

- Dark responsive workflow dashboard for ADAS calibration operations.
- Shop cards for Macon, Perry, and Warner Robins.
- Status columns for Pending Review, Submitted OK, In Progress, Hold, and Complete.
- Sample RO/job cards with vehicle, VIN placeholder, insurance, calibration, due date, status, and notes.
- Projected revenue, completed-count summary cards, search/filter controls, empty states, hold warnings, and a frontend-only Create New Job form.
"""
        html = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ADAS Workflow Command Center</title>
    <link rel="manifest" href="./manifest.json" />
    <link rel="stylesheet" href="./src/styles.css" />
  </head>
  <body>
    <main class="shell">
      <header class="topbar">
        <div>
          <p class="eyebrow">ADAS operations</p>
          <h1>ADAS Workflow Command Center</h1>
        </div>
        <section class="status-strip" aria-label="Status summary">
          <span><strong>18</strong> active jobs</span>
          <span><strong>$24.8k</strong> projected</span>
          <span><strong>7</strong> complete this week</span>
        </section>
      </header>

      <section class="summary-grid" aria-label="Shop summaries">
        <article class="summary-card accent-red"><span>Macon</span><strong>7 jobs</strong><small>2 pending review</small></article>
        <article class="summary-card accent-cyan"><span>Perry</span><strong>5 jobs</strong><small>1 hold warning</small></article>
        <article class="summary-card accent-red"><span>Warner Robins</span><strong>6 jobs</strong><small>4 submitted OK</small></article>
        <article class="summary-card accent-cyan"><span>Completed</span><strong>7</strong><small>$9,450 closed revenue</small></article>
      </section>

      <section class="control-row" aria-label="Workflow controls">
        <label>
          <span>Search jobs</span>
          <input id="search" type="search" placeholder="RO, VIN, vehicle, insurer..." />
        </label>
        <label>
          <span>Shop filter</span>
          <select id="shopFilter">
            <option value="all">All shops</option>
            <option>Macon</option>
            <option>Perry</option>
            <option>Warner Robins</option>
          </select>
        </label>
      </section>

      <section class="board" aria-label="ADAS job board">
        <div class="lane" data-status="Pending Review"><h2>Pending Review</h2><div class="cards"></div></div>
        <div class="lane" data-status="Submitted OK"><h2>Submitted OK</h2><div class="cards"></div></div>
        <div class="lane" data-status="In Progress"><h2>In Progress</h2><div class="cards"></div></div>
        <div class="lane hold-lane" data-status="Hold"><h2>Hold</h2><div class="cards"></div></div>
        <div class="lane" data-status="Complete"><h2>Complete</h2><div class="cards"></div></div>
      </section>

      <section class="form-panel" aria-label="Create New Job">
        <div>
          <p class="eyebrow">Create New Job</p>
          <h2>New calibration workflow</h2>
        </div>
        <form id="jobForm">
          <label>Shop<select name="shop"><option>Macon</option><option>Perry</option><option>Warner Robins</option></select></label>
          <label>RO number<input name="ro" placeholder="RO-1048" /></label>
          <label>VIN<input name="vin" placeholder="VIN placeholder" /></label>
          <label>Vehicle<input name="vehicle" placeholder="2024 Toyota Camry" /></label>
          <label>Insurance<input name="insurance" placeholder="Carrier" /></label>
          <label>Calibration type<input name="calibration" placeholder="Static + Dynamic ADAS" /></label>
          <label>Due date<input name="due" type="date" /></label>
          <label class="wide">Notes<textarea name="notes" placeholder="Parts, scans, targets, or hold reason"></textarea></label>
          <button type="submit">Add frontend job</button>
        </form>
      </section>
    </main>
    <script src="./src/main.js"></script>
  </body>
</html>
"""
        js = """const jobs = [
  { ro: 'RO-1042', shop: 'Macon', vehicle: '2023 Honda Accord', vin: 'VIN-PLACEHOLDER-1042', insurance: 'State Farm', calibration: 'Forward camera + radar', due: 'Today 4:00 PM', status: 'Pending Review', revenue: 1450, notes: 'Awaiting pre-scan upload.' },
  { ro: 'RO-1043', shop: 'Warner Robins', vehicle: '2021 Ford F-150', vin: 'VIN-PLACEHOLDER-1043', insurance: 'GEICO', calibration: 'Blind spot + park assist', due: 'Tomorrow', status: 'Submitted OK', revenue: 1320, notes: 'Customer pickup after final scan.' },
  { ro: 'RO-1044', shop: 'Perry', vehicle: '2022 Kia Telluride', vin: 'VIN-PLACEHOLDER-1044', insurance: 'Progressive', calibration: 'Static camera target', due: 'Fri 10:30 AM', status: 'In Progress', revenue: 980, notes: 'Targets staged in bay 2.' },
  { ro: 'RO-1045', shop: 'Perry', vehicle: '2020 Chevrolet Tahoe', vin: 'VIN-PLACEHOLDER-1045', insurance: 'Allstate', calibration: 'Radar module replacement', due: 'Overdue', status: 'Hold', revenue: 1710, notes: 'Hold warning: missing OEM bracket.' },
  { ro: 'RO-1046', shop: 'Macon', vehicle: '2024 Nissan Rogue', vin: 'VIN-PLACEHOLDER-1046', insurance: 'USAA', calibration: 'Dynamic road test', due: 'Completed Tue', status: 'Complete', revenue: 1225, notes: 'Post scan attached.' }
];

const board = document.querySelector('.board');
const search = document.querySelector('#search');
const shopFilter = document.querySelector('#shopFilter');
const form = document.querySelector('#jobForm');

function render() {
  const query = search.value.toLowerCase();
  const shop = shopFilter.value;
  document.querySelectorAll('.cards').forEach((node) => node.replaceChildren());
  const visible = jobs.filter((job) => {
    const haystack = `${job.ro} ${job.shop} ${job.vehicle} ${job.vin} ${job.insurance} ${job.calibration} ${job.notes}`.toLowerCase();
    return haystack.includes(query) && (shop === 'all' || job.shop === shop);
  });
  document.querySelectorAll('.lane').forEach((lane) => {
    const status = lane.dataset.status;
    const holder = lane.querySelector('.cards');
    const laneJobs = visible.filter((job) => job.status === status);
    if (!laneJobs.length) {
      const empty = document.createElement('p');
      empty.className = 'empty';
      empty.textContent = status === 'Hold' ? 'No hold warnings match this filter.' : 'No jobs in this status.';
      holder.append(empty);
    }
    laneJobs.forEach((job) => holder.append(jobCard(job)));
  });
}

function jobCard(job) {
  const card = document.createElement('article');
  card.className = `job-card ${job.status === 'Hold' ? 'hold-warning' : ''}`;
  card.innerHTML = `
    <div class="job-head"><strong>${job.ro}</strong><span>${job.shop}</span></div>
    <h3>${job.vehicle}</h3>
    <dl>
      <dt>VIN</dt><dd>${job.vin}</dd>
      <dt>Insurance</dt><dd>${job.insurance}</dd>
      <dt>Calibration</dt><dd>${job.calibration}</dd>
      <dt>Due</dt><dd>${job.due}</dd>
      <dt>Status</dt><dd>${job.status}</dd>
    </dl>
    <p>${job.notes}</p>
    <small>$${job.revenue.toLocaleString()} projected</small>
  `;
  return card;
}

form.addEventListener('submit', (event) => {
  event.preventDefault();
  const data = Object.fromEntries(new FormData(form).entries());
  jobs.unshift({
    ro: data.ro || 'RO-DRAFT',
    shop: data.shop || 'Macon',
    vehicle: data.vehicle || 'Vehicle pending',
    vin: data.vin || 'VIN-PLACEHOLDER',
    insurance: data.insurance || 'Insurance pending',
    calibration: data.calibration || 'Calibration pending',
    due: data.due || 'Unscheduled',
    status: 'Pending Review',
    revenue: 0,
    notes: data.notes || 'Frontend-only draft job.'
  });
  form.reset();
  render();
  board.scrollIntoView({ behavior: 'smooth', block: 'start' });
});

search.addEventListener('input', render);
shopFilter.addEventListener('change', render);
render();
"""
        css = """:root {
  color-scheme: dark;
  --bg: #050607;
  --panel: #11161a;
  --panel-2: #171d22;
  --line: #2a343b;
  --text: #f4f8fa;
  --muted: #92a3ad;
  --red: #ff384d;
  --cyan: #20e5ff;
  --amber: #ffb02e;
}

* { box-sizing: border-box; }

body {
  margin: 0;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  background: var(--bg);
  color: var(--text);
}

.shell { min-height: 100vh; padding: 28px; }

.topbar, .control-row, .form-panel {
  border: 1px solid var(--line);
  background: var(--panel);
  border-radius: 8px;
  padding: 20px;
}

.topbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 20px;
}

.eyebrow {
  margin: 0 0 6px;
  color: var(--cyan);
  font-size: 0.76rem;
  font-weight: 800;
  text-transform: uppercase;
}

h1, h2, h3 { margin: 0; letter-spacing: 0; }
h1 { font-size: clamp(1.8rem, 3vw, 3.4rem); }
h2 { font-size: 1rem; }
h3 { font-size: 1rem; margin: 10px 0; }

.status-strip, .summary-grid, .board, .control-row, .form-panel { margin-top: 18px; }

.status-strip { display: flex; flex-wrap: wrap; gap: 10px; }
.status-strip span {
  border: 1px solid var(--line);
  border-radius: 6px;
  padding: 10px 12px;
  background: #0b0f12;
  color: var(--muted);
}
.status-strip strong { color: var(--text); }

.summary-grid {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 12px;
}

.summary-card {
  min-height: 116px;
  display: grid;
  gap: 8px;
  border: 1px solid var(--line);
  border-radius: 8px;
  background: var(--panel-2);
  padding: 16px;
}
.summary-card span, .summary-card small { color: var(--muted); }
.summary-card strong { font-size: 1.8rem; }
.accent-red { border-top: 3px solid var(--red); }
.accent-cyan { border-top: 3px solid var(--cyan); }

.control-row {
  display: grid;
  grid-template-columns: 1fr 220px;
  gap: 14px;
}

label { display: grid; gap: 7px; color: var(--muted); font-weight: 700; }
input, select, textarea {
  width: 100%;
  min-height: 42px;
  border: 1px solid var(--line);
  border-radius: 6px;
  background: #070a0c;
  color: var(--text);
  padding: 10px 12px;
}
textarea { min-height: 88px; resize: vertical; }

.board {
  display: grid;
  grid-template-columns: repeat(5, minmax(220px, 1fr));
  gap: 12px;
  overflow-x: auto;
}

.lane {
  min-height: 420px;
  border: 1px solid var(--line);
  border-radius: 8px;
  background: #0c1114;
  padding: 12px;
}
.lane h2 { padding-bottom: 12px; border-bottom: 1px solid var(--line); }
.hold-lane h2 { color: var(--amber); }
.cards { display: grid; gap: 12px; margin-top: 12px; }
.empty {
  border: 1px dashed var(--line);
  border-radius: 8px;
  color: var(--muted);
  padding: 14px;
}

.job-card {
  border: 1px solid var(--line);
  border-left: 3px solid var(--cyan);
  border-radius: 8px;
  background: var(--panel-2);
  padding: 14px;
}
.job-card.hold-warning { border-left-color: var(--amber); background: #211809; }
.job-head { display: flex; justify-content: space-between; gap: 10px; color: var(--muted); }
.job-head strong { color: var(--red); }
dl { display: grid; grid-template-columns: 86px 1fr; gap: 6px 10px; margin: 0; font-size: 0.88rem; }
dt { color: var(--muted); }
dd { margin: 0; }
.job-card p { color: var(--muted); }
.job-card small { color: var(--cyan); font-weight: 800; }

.form-panel { display: grid; gap: 18px; }
form {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 12px;
}
.wide { grid-column: span 2; }
button {
  min-height: 42px;
  align-self: end;
  border: 0;
  border-radius: 6px;
  background: var(--red);
  color: white;
  font-weight: 900;
  padding: 0 16px;
}

@media (max-width: 980px) {
  .topbar, .control-row { grid-template-columns: 1fr; display: grid; }
  .summary-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }
  form { grid-template-columns: repeat(2, minmax(0, 1fr)); }
}

@media (max-width: 640px) {
  .shell { padding: 16px; }
  .summary-grid, form { grid-template-columns: 1fr; }
  .wide { grid-column: auto; }
}
"""
        return [
            self._file("README.md", readme),
            self._file("index.html", html),
            self._file("src/main.js", js),
            self._file("src/styles.css", css),
            self._file("app/README.md", "Frontend app code lives in `src/`; this folder is reserved for future modular app files.\n"),
        ]

    def _is_adas_prompt(self, prompt: str) -> bool:
        lower = prompt.lower()
        return "adas workflow" in lower or "adas calibration" in lower

    def _requirements_matched(self, prompt: str) -> list[str]:
        if not self._is_adas_prompt(prompt):
            return ["plain_frontend_files", "readme", "manifest", "html", "styles", "app_script"]
        return [
            "dark_dashboard",
            "red_cyan_accents",
            "shop_cards",
            "status_columns",
            "job_cards",
            "revenue_summary",
            "filter_search",
            "create_new_job_form",
            "empty_state",
            "hold_warning",
            "plain_frontend_files",
            "readme",
            "manifest",
        ]

    def _file(self, path: str, content: str) -> GeneratedProjectFile:
        return GeneratedProjectFile(path=path, content=content, sha256=self._hash(content), size_bytes=len(content.encode("utf-8")))

    def _blocked(self, plan: GeneratedProjectPlan, reason: str) -> ProjectBuilderResult:
        plan.status = ProjectBuilderStatus.BLOCKED
        return ProjectBuilderResult(status=ProjectBuilderStatus.BLOCKED, message=reason, plan=plan, wrote_files=False, receipt=self._receipt("project_builder.write_blocked", "blocked", plan, {"reason": reason}))

    def _receipt(self, action: str, status: str, plan: GeneratedProjectPlan, extra: dict[str, object] | None = None) -> dict[str, object]:
        return {"action": action, "status": status, "manifest_hash": plan.manifest_hash, "output_path": plan.output_path, **(extra or {})}

    def _slug(self, value: str) -> str:
        slug = re.sub(r"[^a-zA-Z0-9_-]+", "-", value.strip().lower()).strip("-")
        return slug[:80] or "x8-generated-project"

    def _title(self, slug: str) -> str:
        return " ".join(part.capitalize() for part in slug.replace("_", "-").split("-") if part) or "XV8 Generated Project"

    def _hash(self, content: str) -> str:
        return hashlib.sha256(content.encode("utf-8")).hexdigest()

    def _inside(self, child: Path, parent: Path) -> bool:
        try:
            child.relative_to(parent)
            return True
        except ValueError:
            return False
